---
grafana_version: latest
grafana_yum_repo_template: etc/yum.repos.d/grafana.repo.j2

# Should we use the provisioning capability when possible (provisioning require grafana >= 5.0)
grafana_use_provisioning: true

# Should the provisioning be kept synced. If true, previous provisioned objects will be removed if not referenced anymore.
grafana_provisioning_synced: false

grafana_instance: "{{ ansible_fqdn | default(ansible_host) | default(inventory_hostname) }}"

grafana_logs_dir: "/var/log/grafana"
grafana_data_dir: "/var/lib/grafana"

grafana_address: "0.0.0.0"
grafana_port: 3000

grafana_cap_net_bind_service: false

grafana_welcome_email_on_sign_up: false
grafana_users:
  allow_sign_up: false
  auto_assign_org_role: Viewer
  default_theme: dark

prometheus_web_listen_address: "127.0.0.1:9090"

grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://{{ prometheus_web_listen_address }}'
    basicAuth: false

grafana_dashboards:
  - dashboard_id: 1860
    revision_id: 14
    datasource: prometheus
  - dashboard_id: 2583
    revision_id: 1
    datasource: prometheus
