---
prometheus_version: 2.11.1

prometheus_config_dir: /etc/prometheus
prometheus_db_dir: /var/lib/prometheus

prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_web_external_url: ''

prometheus_storage_retention: "30d"

prometheus_global:
  scrape_interval: 10s

prometheus_external_labels:
  environment: "{{ ansible_fqdn | default(ansible_host) | default(inventory_hostname) }}"

prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  - job_name: 'node-exporter-monitoring'
    static_configs:
      - targets:
        - "10.150.0.26:9100"
  - job_name: 'node-exporter-db'
    static_configs:
      - targets:
        - "10.150.0.27:9100"
  - job_name: 'mongodb-exporter-db'
    static_configs:
      - targets:
        - "10.150.0.27:9216"
  - job_name: 'rabbitmq-exporter-db'
    static_configs:
      - targets:
        - "10.150.0.27:9419"
