---
- name: Install GitLab
  hosts: gitlub
  become: true

  task:

  - name: Install runner
    shell: docker run -d --name gitlab-runner --restart always -v /srv/gitlab-runner/config:/etc/gitlab-runner -v /var/run/docker.sock:/var/run/docker.sock gitlab/gitlab-runner:latest 

  - name: Registration runner
    shell:  docker exec -it gitlab-runner gitlab-runner register --run-untagged --executor shell --locked=false
