---
- name: Install GitLab
  hosts: gitlab
  become: true

  tasks:

  - name: Copy compose file
    copy:
      src: ../files/docker-compose.yml
      dest: /home/r2d2

  - name: Docker compose up
    shell: cd /home/r2d2 && docker-compose up -d

