---
- name: Install MongoDB
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:

  - name: Add mongo ppa key
    sudo: yes
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: 9DA31620334BD75D9DCB49F368818C72E52529D4
      state: present
      
  - name: Add mongo sources list
    sudo: yes
    lineinfile:
      line: "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse"
      dest: /etc/apt/sources.list.d/mongodb-org-4.0.list
      state: present
      create: yes

  - name: Install mongo
    sudo: yes
    apt: 
      name: 'mongodb-org=4.0.10'
      state: present
      update_cache: yes
